### ISSUE TITLE
Actualizado de foto 

### ISSUE THREAD

**Issue by cads918** [lmlopezmagana/satapp#13]
Si el usuario no tiene foto de perfil la petición de actualizado de foto te devuelve un 400.

**Comment by cads918** [comment]
2020-03-06T07:28:55.515107+00:00 heroku[router]: at=info method=PUT path="/users/5e5624398066e6547840368e/img" host=satappgroupfive.herokuapp.com request_id=e613516f-1e19-41fe-8474-d31f0d0966b4 fwd="85.137.19.11" dyno=web.1 connect=2ms service=794ms status=500 bytes=459 protocol=https
2020-03-06T07:28:55.514042+00:00 app[web.1]: PUT /users/5e5624398066e6547840368e/img 500 790.450 ms - 148
2020-03-06T07:28:55.547264+00:00 app[web.1]: TypeError: Cannot set property 'data' of undefined
2020-03-06T07:28:55.547266+00:00 app[web.1]: at /app/src/api/user/controller.js:118:7
2020-03-06T07:28:55.547266+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by lmlopezmagana** [comment]
Solucionado en 6e53963d6e5b572479ff756ec3e8ffb2aaa6a06a
